### ISSUE TITLE
Initial account can not be imported

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1052]
WTR:

1. Open desktop wallet
2. Copy mnemonic from paper wallet
3. Import an account with mnemonic

Result: When I import the account with mnemonic I don't see imported account in the list [Video](https://www.loom.com/share/487be2fcad5a4dc2ae0d0e7bf8f97a71)  

If I take the first one, it creates new empty account.

**Comment by OlegMakarenko** [comment]
Also it shows an incorrect notification: `Successfully generated a random mnemonic passphrase`

**Comment by OlegMakarenko** [comment]
@NikolaiB are you using mnemonics generated with the latest wallet version?

**Comment by NikolaiB** [comment]
@OlegMakarenko I am using the Paper Wallet generated with 0.13.8 wallet version.

**Comment by cryptoBeliever** [comment]
@NikolaiB in 0.14.0 new derivation path for testnet was introduced. So your old seed will generate new addresses. That's why when we release wallet in announcement release will be information to backup first private keys if you need those accounts.

@OlegMakarenko reported as seperated issue https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1058
