### ISSUE TITLE
Don't allow skip mnemonic confirmation for Mainnet

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1188]
1. Please remove "Skip" option on mnemonic confirmation when creating Mainnet profile (for Testnet is OK to keep it).

![image](https://user-images.githubusercontent.com/17684281/108626970-4eea0800-7453-11eb-823a-077bcb249800.png)

2. Also "Backup Phrase" allow you to click "Next" without checking and making backup of mnemonic.

![image](https://user-images.githubusercontent.com/17684281/108630166-bf008a00-7463-11eb-86c1-403fe0638d90.png)

**Comment by jabo38** [comment]
I think there is a second option which is on the mainnet if a person chooses to skip, then there is a big warning message that they can't get rid of until they prove they have backed it up. 

The reason is that some users want to just "check out a wallet" to look around before they buy or test. To go through the process of backing up and re-entering the 24 words stops some people from checking out the wallet. 

But I agree with the general point that it is important to make people back up their wallet. Otherwise people don't do it and lose funds.

**Comment by cryptoBeliever** [comment]
Fixed.
