### ISSUE TITLE
Offline transactions not working for mainnet

### ISSUE THREAD

**Issue by Peersyst** [nemgrouplimited/symbol-desktop-wallet#1369]
1. Trying to import a tx that needs an offline signer to sign via QR code doesn’t work. I tested on two computers and 2 OS, Mac and Ubuntu. Scanning the QR code makes no result in the offline cosignature page.

2. from a single account private key, I’m able to create an offline tx. From the dashboard of an online machine I go to  scan QR, i’m able to scan it and announce to the network but the tx fails because “tx is too far in the future”. In the past, both of these things worked, so I guess it is a small issue.

**Comment by jabo38** [comment]
I tested both of these issues and had these failures.

**Comment by surekabpm** [comment]
@AdriaCarrera Im not able to test in mainnet. I downloaded the branch code and tested in testnet. The steps I followed 
1. created multisig accounts with 1 cosignor, 
2. dowloaded the cosignor QR code
3. logout , go to offline transactions
4. select the cosign profile and import the QR code and confirm the transaction sign successfully by giving password
5. now logged in again and saw in the cosign account is still not signed in ...
I believe the issue is not fixed. 
![image](https://user-images.githubusercontent.com/49143210/113258430-8e750100-92e9-11eb-8d41-c7bb24153101.png)
![image](https://user-images.githubusercontent.com/49143210/113258501-a3ea2b00-92e9-11eb-89dd-1c861edf8378.png)

**Comment by Peersyst** [comment]
Once you sign the offline transaction, you have to download the QR code and sign in using any profile. Then go to the import profile button on the top of the screen and drag-and-drop the downloaded QR code. Proceed with the steps and then the transaction will be broadcasted to the network. Otherwise the transaction never goes online

**Comment by surekabpm** [comment]
based on above comments, the offline transaction was signed and QR code downloaded, then logged in with a user and import QR code, and it was broascasted (but this was in testnet) we need to get it tested in mainnet 
![image](https://user-images.githubusercontent.com/49143210/113285289-6b0d7e80-9308-11eb-9b7b-9ca0366c52df.png)
![image](https://user-images.githubusercontent.com/49143210/113285342-795b9a80-9308-11eb-83ce-f918edf6f7e0.png)
