### ISSUE TITLE
Offline transaction - missing transaction details when cosignature imported using Payload

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1387]
Steps:
1. Open offline transactions
2. "Cosign Transaction" tab
3. Import cosignature by payload

Results: Transaction details are not presented and we are going to transaction signing.

Expected result:
Present transaction details as is done for import payload by QR:

![image](https://user-images.githubusercontent.com/17684281/113423613-197bf700-93cf-11eb-880b-39ac34021735.png)

**Comment by surekabpm** [comment]
@AdriaCarrera i'm getting error while extracting files from zip file , if i skip those errors that is causing issues while running the npm run dev code , please have a look

**Comment by surekabpm** [comment]
This issue is retested and passed, can be merged to main branch. Steps I followed 1. create multisig accounts 2. go to offline transactions,select cosign transaction,import the QR code, click continue , then close the pop up, you will get sign transaction 3.enter the password and the transaction is signed 
![image](https://user-images.githubusercontent.com/49143210/113819079-704e4b80-9796-11eb-9e5a-805bbf88ba4f.png)
![image](https://user-images.githubusercontent.com/49143210/113819136-852adf00-9796-11eb-8c0d-78b321104285.png)
![image](https://user-images.githubusercontent.com/49143210/113819208-a12e8080-9796-11eb-9345-019c8a427cc9.png)
![image](https://user-images.githubusercontent.com/49143210/113819247-aee40600-9796-11eb-86ce-e1fc7f04c2f2.png)

**Comment by surekabpm** [comment]
transaction was signed in by importing the QR code online 
![image](https://user-images.githubusercontent.com/49143210/113819720-56613880-9797-11eb-843b-02dabc72dca6.png)

**Comment by surekabpm** [comment]
I tried with the payload and the transaction was signed successfully, 
![image](https://user-images.githubusercontent.com/49143210/113873666-a27d9e80-97d2-11eb-946f-054a055247b9.png)
![image](https://user-images.githubusercontent.com/49143210/113873734-b32e1480-97d2-11eb-87d0-e9b9941761c9.png)
![image](https://user-images.githubusercontent.com/49143210/113873787-c04b0380-97d2-11eb-8e9b-afd1b92e7e13.png)

**Comment by surekabpm** [comment]
while pasting the payload , first time not getting teh pop up but if I deete it go back to login page and come back to offline transaction and paste the same code , pop up of teh transaction appears 
![image](https://user-images.githubusercontent.com/49143210/113877695-9398eb00-97d6-11eb-890d-e6cbcff78765.png)

**Comment by surekabpm** [comment]
i used the below payload F8000000000000004402C778AB7380D0E8AE802A35D3324E484A72426B5F1702E9703E1720B2423B3E08980805A9B28EE7ECC8E26CAF6F7A86E7ACA408338066DF568DAA3918BB0932D3CAE58228B217F247B735D922CF477BC161042D2B69515A3BA2ACFB9D54BC000000000198414280402F0100000000704F705D0A0000005451AAEF3D419DCF62B3135D69BA2E553FF8D69E1295FC090D97A5585ADCCF4D5000000000000000500000000000000032D3CAE58228B217F247B735D922CF477BC161042D2B69515A3BA2ACFB9D54BC0000000001985541010101000000000098270851CACD47A2D5FC6B86B8AF584D0487A616FCF44684

**Comment by surekabpm** [comment]
Tested and can be closed
