### ISSUE TITLE
Offline transaction - Simple transaction not possible offline

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1389]
Wallet version: 1.0.1 for Linux

Steps:

1. Clear all profiles/settings (Linux ~/.symbol-desktop-wallet)
2. Open wallet
3. Create wallet
4. Logout
5. Go to Offline Transaction (Simple Transaction tab) - Offline Transfer transaction view is not visible entirely

![image](https://user-images.githubusercontent.com/17684281/113426048-2c90c600-93d3-11eb-842f-a6eba19d3bd4.png)

6. Switch to Cosign transaction view.
7. Switch back to "Simple transaction view". You got information "The wallet could not load data about the network currency (e.g. symbol:xym), please connect to a valid node.". And not possible to init transaction.

![image](https://user-images.githubusercontent.com/17684281/113426103-3fa39600-93d3-11eb-8826-096dd3272c3e.png)

**Comment by surekabpm** [comment]
This issue is fixed and tested .. this PR can be merged
![image](https://user-images.githubusercontent.com/49143210/113815458-cc15d600-9790-11eb-8c74-dbf8bc75f9b4.png)
![image](https://user-images.githubusercontent.com/49143210/113815479-d932c500-9790-11eb-81cc-1841e7e78364.png)
No error while switching back from cosign transaction to simple transaction 
![image](https://user-images.githubusercontent.com/49143210/113815523-ef408580-9790-11eb-8bad-40fa9b171d9d.png)

**Comment by surekabpm** [comment]
This issue is tested , not getting the error while switching tabs and simple transaction is possible during offline .this can be closed
