### ISSUE TITLE
QR codes and URI handling

### ISSUE THREAD

**Issue by decentraliser** [nemgrouplimited/symbol-desktop-wallet#249]
I guess we will need UI mockups for this one

1. Make a service that takes a URI as an input, and returns a FormattedTransaction
2. Make a service that takes a QR code and returns the object and Qr Type
3. In a view, enable image input through file and/or camera
4. In a view, enable transaction detail view and signature from an URI input

- `AccountQR`: Propose to import as a private key
- `ContactQR`: Propose to redirect to transfer with contact as recipient
- `CosignatureQR`: Using service 1. , pop up transaction confirmation if OK
- `MnemonicQR`: Propose to create a new account (enabling copy-paste) (no redirect, I guess we should put a QR option in the account import process)
- `ObjectQR`: Show the object
- `TransactionQR`: Using service 1. , pop up transaction confirmation if OK

**Comment by yilmazbahadir** [comment]
Implementation is designed based on the following decisions (as discussed with @evias) 

- All of the QR Code Imports will be done via Top Menu -> "Import QR Code" menu item -> Import QR Modal Page for user's convenience.
- A wizard will be presented, user will upload a valid QR Code, after the QR Code type is identified, user will be taken to the next step where she can view the details of the QR Code and preview the action will be taken.
- A password form will be shown for the following protected QR Codes(if not pwd protected, form will not be shown)
    - MnemonicQR
    - AccountQR
- User can continue to take the following actions:
    - ContactQR ⇒ Redirect to transfer page with contact as recipient
    - MnemonicQR ⇒ Copy the Mnemonic passphrase to the clipboard and redirect to create profile page
    - TransactionQR ⇒ Redirect to the transfer page with the details filled, user should only need to click send and sign.
    - ObjectQR ⇒ Show the JSON Object
    - (to be implemented) AccountQR ⇒ Redirect to add an account modal page / import as private key w/ all the fields filled.
    - (to be implemented) CosignatureQR ⇒ Redirect to the transactions page open transaction confirmation modal.

At the moment following features are missing in the desktop-wallet app and need to be implemented in order to complete this issue.

- AccountQR Export (issue #xxx)
- CosignatureQR Export (issue #xxx)

**Comment by yilmazbahadir** [comment]
> 1.Make a service that takes a URI as an input, and returns a FormattedTransaction
> TransactionQR: Using service 1. , pop up transaction confirmation if OK

I couldn't see the link between TransactionQR and TransactionURI. Can you @evias @decentraliser please elaborate on this and the following ? 

If there is no link (or there is a loose one) it would be better to handle "Transaction URI Handling" in another issue. In any case outline of the desired view and how to access that view need to be elaborated.

**Comment by yilmazbahadir** [comment]
As discussed with @evias TransactionURI handling will be handled with a different ticket (#509).
