### ISSUE TITLE
Network Static Panel showing accounts instead of transactions

### ISSUE THREAD

**Issue by fboucquez** [nemgrouplimited/symbol-desktop-wallet#358]
The UI states **Transactions** but it is actually showing **Accounts**

![image](https://user-images.githubusercontent.com/5390558/82131202-0b1df000-97a9-11ea-87f4-189e552cdfa0.png)

It mean just be a label problem but do we want to show accounts, transactions, or both?

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/language/en-US.json#L239

https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/components/NetworkStatisticsPanel/NetworkStatisticsPanel.vue#L6

Would it be possible to remove Animation and use a static number? I think it is a bit annoying to wait for the counter to finish every time you go back to the dashboard. If it's a loading issue, to avoid jumping from 0 to a real number, we could add a loading spinner, storage cache and/or prefetch data while logging in.

**Comment by evias** [comment]
use `Accounts` there, and put the Transactions counter at the place of `Speed` :+1:

I agree the number animation is not really adding any value to the component.

**Comment by evias** [comment]
the reason why harvesting is not available for “Private Key PRofiles” ; is because harvesting is a multi account involving process:

1. since 963 there is VRF Keys for any account who wants to harvest.
2. there is also a notion of linked account keys (“remote account”)

and so, those 1 and 2 accounts, we create them automatically with HD wallets …. one mnemonic, many accounts, easier on the end-users

would we allow it for Private Key Profiles, it would mean that there is a possibiltiy for people to *lose information* related to their remote and VRF accounts, which is inacceptable. 

So we decided to lock the feature for HD Profiles only until we have an automatic "backup verification" for remote and VRF accounts in place for non-HD profiles. 

The issue #221 has precedence over the implementation of harvesting for private key profiles.
