### ISSUE TITLE
Message Transfer transaction contains 0 XYM 

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#474]
I tried to make just a message Transfer transaction without mosaic.

**Current behaviour**
Mosaics property is `mosaics: [{id: "5E62990DCAC5BE8A", amount: "0"}]`
![image](https://user-images.githubusercontent.com/33131259/87974626-04766680-cad3-11ea-81f3-745a62ba274f.png)
![image](https://user-images.githubusercontent.com/33131259/87969743-629f4b80-cacb-11ea-9d9d-db8f551eeb4e.png)
![image](https://user-images.githubusercontent.com/33131259/87969784-72b72b00-cacb-11ea-82d6-d2b0cea0e5bc.png)

**Expected behaviour**
Mosaics property should be an empty array
![image](https://user-images.githubusercontent.com/33131259/87974549-e6a90180-cad2-11ea-86e8-1de6620f4ea0.png)

**Comment by evias** [comment]
Thank oleg for that report ; 

It is perfectly valid to add the mosaic without amount as an attachment.

As a proposed feature enhancement **we could add the Trash icon** next to the _first line_ as well **OR** we must make sure that the end-user knows what is happening when they put `0` because 0 is a valid amount of mosaic to be attached. You could for example think of a free timestamping solution that uses a mosaic but never sends amounts.. 

Please provide with more details to enhance the user experience around empty mosaic attachments.
