### ISSUE TITLE
Transaction list - amount column

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#508]
Wallet: v0.12.1

According to my talk with @evias Transaction list "Amount" column should present:
- if one of the sent mosaics is XYM then amount column should present sent XYM amount
- if there is no XYM mosaic but there are other mosaics then "Amount" should present first mosaic on list (from sent mosaics) amount
- if there are no mosaics sent "Amount" should present as is now (N/A)

Right now XYM is not prevails and always first mosaic Amount is presented. Examples below.

![image](https://user-images.githubusercontent.com/17684281/92324935-ab44a100-f046-11ea-9c31-5a718792e507.png)

![image](https://user-images.githubusercontent.com/17684281/92324936-aed82800-f046-11ea-9dc2-caf620545908.png)

**Comment by jabo38** [comment]
The majority of txs will, at first anyway be XYM, and will not be aggregates, so this won't be a big issue right off. 

But never-the-less, this is very valid and as makers of this wallet, XYM, should always go first. 

In the case there are more than one mosaic, it could be nice to have a (+) sign after XYM. 

In the case that it was not XYM, we could maybe even use a different color to show the amount. Maybe a shade or two lighter or darker or a bit more greenish or purplish. 

Maybe not necessary, but might be nice to think about. 

I don't necessarily like the idea of writing (XYM) or (67D3B7250883745D) on each line because that becomes very ugly and cluttered but a (+) or a different color might do the trick to make a better user experience as both of those are very minimal.

**Comment by cryptoBeliever** [comment]
@OlegMakarenko I think you created similar one. Presenting in amount column only if native coin was sent would fix that.

**Comment by yilmazbahadir** [comment]
@OlegMakarenko, @cryptoBeliever  can we close this if this is a duplicate or irrelevant.

**Comment by cryptoBeliever** [comment]
When https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1090 will be done we can probably close. For now, I would leave open.

**Comment by bassemmagdy** [comment]
@cryptoBeliever should be closed when #1505 is merged

**Comment by cryptoBeliever** [comment]
transaction 1:
- 2 mosaics (without symbol.xym)
transaction 2:
- without mosaics at all. with message
transaction 3:
- with mosaics (2XYM, 1 702AFE86F22BEEAF, 3 7C0E12FB21F32D9A)

- I don't see mosaics icon. BUG
- if there is no XYM should we present amount as other mosaic amount? BUG

![image](https://user-images.githubusercontent.com/17684281/121564910-390d4c80-ca1c-11eb-9ec9-2bdd20c61cf8.png)

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
Problem on branch sprint-fixes described https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1090#issuecomment-862602156

**Comment by bassemmagdy** [comment]
@cryptoBeliever just merged the changes into sprint-fixes branch

**Comment by cryptoBeliever** [comment]
Thanks. 
https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1090#issuecomment-860182758 is still not fixed.

**Comment by cryptoBeliever** [comment]
Not merged. Moving to feature testing.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
