### ISSUE TITLE
TransactionURI import & export feature

### ISSUE THREAD

**Issue by yilmazbahadir** [nemgrouplimited/symbol-desktop-wallet#509]
User should be able to export/import a transaction as a TransactionURI (see https://github.com/nemtech/symbol-uri-scheme ).

* TransactionURI Export: On the transfer page, the send button should be changed into a dropdown action button (with preserving the default send button behaviour intact), as an optional action export to TransactionURI should be clicked and URI should be shown on a modal page to copy.

* TransactionURI Import: Can be a modal page being opened by a Top bar menu item or can be another tab to the dashboard transfer tabs

**Comment by yilmazbahadir** [comment]
As discussed with @evias, following changes has been applied to the design:

* Instead of modal export transaction URI page, transaction URI is shown on the bottom of the transfer page and it gets updated live as the user fills the details.
* When the user hovers over the link icon a Tooltip is shown and a Poptip is shown for the full version of the transaction URI when  user clicks the shortened transaction URI. A copy button for the user to easily copy the transaction URI.

@jabo38 could you also review and share your thoughts on this?

Following are the screenshots of the implementation:

![Screenshot 2020-09-25 at 20 35 01](https://user-images.githubusercontent.com/6256269/94310897-45c34080-ff72-11ea-99d9-b6cbbf1d0b10.png)

![Screenshot 2020-09-25 at 21 02 30](https://user-images.githubusercontent.com/6256269/94311398-1d881180-ff73-11ea-918a-8227aa74ce7e.png)
![Screenshot 2020-09-25 at 21 02 43](https://user-images.githubusercontent.com/6256269/94311420-28db3d00-ff73-11ea-85d1-ae8442823d4c.png)

![Screenshot 2020-09-25 at 20 35 24](https://user-images.githubusercontent.com/6256269/94310834-2debbc80-ff72-11ea-8cae-7a1a9985d8c7.png)

**Comment by jabo38** [comment]
My preference for exporting the transaction URI is to have it in small grey and truncated letters underneath the transaction. 

![image](https://user-images.githubusercontent.com/10395907/94315608-75f5e980-ff48-11ea-89cb-dea40a2f717b.png)

This is this a very advanced feature on a page where more than 99% of people will be doing a simple thing, I'd suggest, having an little explainer button in the top right of the info box where people could understand just more what a transaction URI is for. 

This would mean the send button is just a normal send button I guess then and won't have an arrow on it?

As per importing, I don't think it looks bad where it is at, and don't have any suggestion how to make it better.

**Comment by jabo38** [comment]
I don't understand why the export transaction URI is on the send screen. In that scenario, I'm guessing the transaction still needs to be signed. So why would somebody take a transaction URI that they haven't signed, then import it into another wallet where they would have to sign it. 

I think it makes more sense to put it in the screen where a person has already entered their password and are signing the tx. 

So in theory, I would going to the confirm screen, entering my password, but instead of clicking "confirm", I would click on a drop down arrow on the confirm screen that would give the option to export tx as a URI. 

![image](https://user-images.githubusercontent.com/10395907/94316931-e9005f80-ff4a-11ea-8104-99d77118bb27.png)

And since this is a very advanced feature, but on a page where 99% of people won't be doing something advanced, it would be nice if they were clicking on signed tx as URI, that they were given a way to have an explainer of what they were doing or why they would want to do it. 

![image](https://user-images.githubusercontent.com/10395907/94317082-29f87400-ff4b-11ea-9e27-0d24b41e7abf.png)

As for import tx URI, it doesn't look bad where it is in the screen shots and I don't have any suggestions how to improve it.

**Comment by yilmazbahadir** [comment]
I think URI Scheme Library doesn't support representing already signed transactions.

Because it says "URI Scheme library to serve Symbol transactions ready to be signed." in the library repo (https://github.com/nemtech/symbol-uri-scheme).
