### ISSUE TITLE
Multisig - Unable to remove all cosigners and convert back to single account

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#529]
Version: v0.13.1

I'm unable to remove cosigner from 1 of 1 multisig (probably other multisig too). I'm getting error "Failure_Multisig_Min_Setting_Out_Of_Range"

![image](https://user-images.githubusercontent.com/17684281/94922289-400db380-04ba-11eb-80a2-122f36b144c8.png)

![image](https://user-images.githubusercontent.com/17684281/94922314-469c2b00-04ba-11eb-8caf-22ae977d5906.png)

**Comment by yilmazbahadir** [comment]
User should be able to convert multisig back to single account by removing all cosigners.

When a user is removing cosigners from 1 of 1 (on desktop wallet) and changing min. approval and min. removal to 0
he gets error "Failure_Multisig_Min_Setting_Out_Of_Range".

Websocket communication (after hash lock announced):
{"topic":"partialAdded/TB2FXWD7CNGIRRGCKJYSDB4H6Q7I3J6QZSVBNLA","data":{"transaction":{"signature":"64F29B2CE434FCB93F1FAADCE144BA3F5C9C43FE4D4E983B93D462661145E5CF4B31B36E14AA85E9351BD49742FD30CAC313CD3FDC1C68191052C7B130121204","signerPublicKey":"AE9941F3BDF384CC5009A41DCBD1626671818AA4C2B3E479E2FF411648C03C38","version":1,"network":152,"type":16961,"maxFee":"248000","deadline":"28212349752","transactionsHash":"0AE21F0F8A2D1F72952DAA522C002FA2A4253F734B6BDDEDFD7CC5C86974DB95","transactions":[{"transaction":{"signerPublicKey":"36EB40E838593D446C31D04F9F94792545BE7DF8828A1D66AA08043085808274","version":1,"network":152,"type":16725,"minRemovalDelta":-2,"minApprovalDelta":-2,"addressAdditions":[],"addressDeletions":["989B38504A3064781DD549DE17C0C5F7F5E4A4607F66D742"]}}]},"meta":{"hash":"B4E4D27284364ED2CDD11CAE9F1A3D381DF7D85691B62826162D2CB21202059C","merkleComponentHash":"0000000000000000000000000000000000000000000000000000000000000000","height":"0"}}}
{"topic":"partialRemoved/TB2FXWD7CNGIRRGCKJYSDB4H6Q7I3J6QZSVBNLA","data":{"meta":{"hash":"B4E4D27284364ED2CDD11CAE9F1A3D381DF7D85691B62826162D2CB21202059C"}}}
{"topic":"status/TB2FXWD7CNGIRRGCKJYSDB4H6Q7I3J6QZSVBNLA","data":{"hash":"B4E4D27284364ED2CDD11CAE9F1A3D381DF7D85691B62826162D2CB21202059C","code":"Failure_Multisig_Min_Setting_Out_Of_Range","deadline":"28212349752"}}

SDK's test regarding the way it should work:

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/194e1a330874a9f6141938d2f4e1b333e5657c79/e2e/infrastructure/AccountHttp.spec.ts#L264

**Comment by cryptoBeliever** [comment]
@yilmazbahadir above websockets output is when I manually changed minRemovalDelta to -2 (instead -1 when you choose 0 as a min approval and min removal on form). But for 0 there is same error (Failure_Multisig_Min_Setting_Out_Of_Range)

**Comment by yilmazbahadir** [comment]
I'm unable to reproduce the issue, even I've tried multiple times.

But when I checked the code I saw that there are 2 cases that error could be returned. 

On the first case, when it couldn't find the multisig object in the cache, it expects minRemovalDelta and minApprovalDelta to be exactly -1 , otherwise it returns an error.
https://github.com/nemtech/catapult-server/blob/2fed617dc514aba37698edced71357c0b0cb56fd/plugins/txes/multisig/src/validators/MultisigInvalidSettingsValidator.cpp#L43

And the second case is when it can find the multisig object it checks if the minRemoval and minApproval is less than 1 and return the error if not. 
https://github.com/nemtech/catapult-server/blob/2fed617dc514aba37698edced71357c0b0cb56fd/plugins/txes/multisig/src/validators/MultisigInvalidSettingsValidator.cpp#L52

I believe this error happened because the wallet wasn't able to update the account via websocket at the first attempt even the transaction was successful. This might be due to a network issue or rest wasn't able to push the message at the time. To restore the account, you can switch to a different account and switch back to verify this is the case, if you face the same issue again. If that's the case we can prevent it programmatically by calling the multisigaccountinfo API endpoint to refresh.

**Comment by cryptoBeliever** [comment]
@yilmazbahadir I'm unable to reproduce now too (on main and on tag v0.13.1)
