### ISSUE TITLE
Mosaic transactions in aggregate, "Supply" is not set.

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#704]
As the title says.

**Comment by cryptoBeliever** [comment]
There is also no way to set supply (no input)

**Comment by bassemmagdy** [comment]
Hey @trestoJP, The reason behind that is that you can't bundle aggregate transactions inside each other. In the case of mosaic creation aside from aggregates. Firstly, we initiate MosaicDefinitionTransaction to create a mosaic then we initiate MosaicSupplyChangeTransaction to provide the funds/supply for that mosaic, meaning that the creation of mosaic with funds is an aggregate transaction itself.

In Aggregate transactions we just allow users to initiate MosaicDefinitionTransaction(first-step), after that to change the supply of that mosaic they have to go update it from Mosaic list page.

**Comment by cryptoBeliever** [comment]
@bassemmagdy but this implies the creation of a mosaic with mutable supply because without this there will be no way to change supply. As it turned out such mosaic without supply is not visible too on mosaics list... Maybe can we flatten txs into one aggregate without nesting?
Please check https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/723
