### ISSUE TITLE
Two same namespace is created

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#743]
I believe namespace is identical and unique, i have created two namespace name_980 , it has accepted and transaction is confirmed..  in transaction they are confirmed but in the namespace it is not listed twice..
@yilmazbahadir  please check this address key - TB3KWQJRW7QIW3IVFCPIE6L4CYGTG44NGU3BOOQ
![image](https://user-images.githubusercontent.com/49143210/100317322-284a3b80-2fe2-11eb-92f2-c6d99dc6b89c.png)
![image](https://user-images.githubusercontent.com/49143210/100317513-7bbc8980-2fe2-11eb-9237-605c51513926.png)

**Comment by yilmazbahadir** [comment]
As far as I can see they are not identical => "name_980" != "name_9**9**0"

**Comment by surekabpm** [comment]
please scroll little down and check the namespace transaction
![image](https://user-images.githubusercontent.com/49143210/100319914-6ea19980-2fe6-11eb-9da3-bdcf7567a1f3.png)

**Comment by yilmazbahadir** [comment]
Okay, checked with the PK provided. I think, this is the expected behaviour, the owner account of the namespace can send the tx with the same name again but a different account cannot use the same name(it gives the error attached)

![Screenshot 2020-11-26 at 07 55 06](https://user-images.githubusercontent.com/6256269/100323194-4487b180-2fbd-11eb-8cfe-597223b7f293.png)

**Comment by surekabpm** [comment]
ok, thanks for the clarification.closing the issue
