### ISSUE TITLE
Problem with reading Invoice with encrypted message

### ISSUE THREAD

**Issue by bassemmagdy** [nemgrouplimited/symbol-desktop-wallet#794]
- There is a problem with reading Invoice with encrypted message.
A) Go to Invoice view (address is filled by default).
B) Put random message
C) Check encrypted message
D) Get generated QR and try import it using Import QR Code (in top menu)

Result: Message is imported as unencrypted. Also "Encrypt" button is not checked. Same problem when we using "Importing transaction URI" from Invoice view on Transfer view.

**Comment by cryptoBeliever** [comment]
Now after importing QR with encrypted message I'm ending with:

![image](https://user-images.githubusercontent.com/17684281/103103979-fbab3300-4624-11eb-8f22-f0e73f86f6d0.png)

QR I importing:
![image](https://user-images.githubusercontent.com/17684281/103104019-28f7e100-4625-11eb-8b28-0c21d70187e4.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko 
1) After this change mobile wallet is unable to read encrypted QR correctly because encryption works there differently. As a result, the mobile wallet is trying to encrypt an encrypted string.
We want handle encrypted messages in this way? I would prefer to present the user not encrypted string but what user-provided as an input. As I understand there is a problem with QR's.
2) Maybe after check "encrypted" checkbox we should block a user to not allow modify encrypted string?

**Comment by james-lin71** [comment]
@cryptoBeliever 

1. Not really, that is not what we excepted and it might be an issue. If you can upload a example video for your case, then that would be great, because that works well on my side. I would like double check on this.
2. QR import logic might be limited for all of global users, in terms of encryption logic is using private key. I suppose it have to be work for any QR codes, even though they are comes from other users. To make this happen, we might be change encryption logic to be like RSA encryption, so that any encrypted message can be decrypted by user's public key.
Or is this functionality was just for a user?

**Comment by OlegMakarenko** [comment]
@cryptoBeliever I will have a look at the mobile wallet issue
@james-lin71 It doesn't work on the desktop wallet when signer !== recipient. The message field is empty after decryption

**Comment by cryptoBeliever** [comment]
@james-lin71 @rg911 

What is needed to encrypt message?
Isn't it sender private key and recipient public key? If yes then how we can calculate encrypted message at time of generating the invoice? For me, it doesn't make sense, and don't have chance to work.

In my opinion:
1) Invoice message encryption doesn't have the sense and chances to work. It should be removed.
2) For regular transfer transactions we should not replace and present encrypted string to the user (it should be done in the background and the user should see always message). Here odd bahaviour I'm talking about -> https://share.getcloudapp.com/Z4u6KP4b

**Comment by rg911** [comment]
I think for invoice generation, the encrypted message can be hidden (not allowed), as the sender's private key and the recipient's publicKey both are required.

**Comment by cryptoBeliever** [comment]
@james-lin71 
Please remove "Encrypt the message" from the Invoice view

**Comment by cryptoBeliever** [comment]
Fixed.
