### ISSUE TITLE
Not possible to create more than 10 accounts

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#929]
After you have logged in to a profile it is not possible to create/add more than 9 additional accounts. It should be unlimited.

**Comment by jabo38** [comment]
I tested this and I'm not sure why it is limited to only 10. It should be unlimited. Many people use A LOT more than 10 addresses.

**Comment by cryptoBeliever** [comment]
@rg911 wasn't this intentional? I mark as enhancement for now

**Comment by jabo38** [comment]
A long time ago when the wallet was being made, I had suggested that there be around 10 accounts given as a start. That’s because few people need 10 accounts when starting. But it wasn’t ever supposed to be a hard limit. 


I also suggested that as long as there are accounts with funds they should be listed. 

So for instance, if my first 20 accounts from the seed all have funds, all 20 should be shown. If there are 50, then all 50 should be shown. Only show 10 if the balances at the end are 0. 

The mobile app also lets you add lots of accounts. And in fact, as far as I know you can optin more than 10 accounts on mobile too. In which case those 10+ Symbol accounts should preload after launch. Or at least that’s how I requested it back then.

**Comment by jabo38** [comment]
I personally think it’s more than an enhancement. Like why only allow 10 when the mobile and optin allow more.

**Comment by cryptoBeliever** [comment]
@jabo38 the question is if we need it at start? What you think?

**Comment by cryptoBeliever** [comment]
@jabo38 for now marking as P3. Please let me know how you feel about that.

**Comment by garm01** [comment]
With more than ten accounts, it might also make sense if the user can sort the accounts according to his imagination. At the moment, he only has this option when importing the Mnemonic Passphrase or when creating the wallet.

**Comment by jabo38** [comment]
@cryptoBeliever if it isn't on a launch release, it needs to be on the release after launch. 

I don't know of a single other crypto wallet that limits addresses to only 10. 

10 to start? sure.... okay. I have seen that kind of thing before. But a hard limit of 10. Not ever.

**Comment by cryptoBeliever** [comment]
Ok. Increasing to P2.

**Comment by Eugenity** [comment]
Verified. Closing.
